FRAME_SAMPLE_FPS = 2.0

CROP_X = 1470
CROP_Y = 0
CROP_W = 450
CROP_H = 225

DEDUPE_WINDOW_SECONDS = 2.0
MERGE_WINDOW_SECONDS = 8.0
CLIP_PRE_SECONDS = 15.0
CLIP_POST_SECONDS = 0.0
FUZZY_MATCH_THRESHOLD = 78

LOCAL_TEMP_DIR = "./temp"
LOG_LEVEL = "INFO"
LOCAL_HELPER_HOST = "127.0.0.1"
LOCAL_HELPER_PORT = 4001
LOCAL_HELPER_PUBLIC_BASE_URL = ""
ANALYSIS_API_BASE_URL = ""
ANALYSIS_API_PATH = "/analyze"
ANALYSIS_REQUEST_TIMEOUT_SECONDS = 30
MAX_UPLOAD_BYTES = 300 * 1024 * 1024
MAX_CONCURRENT_JOBS = 1
KEEP_JOB_ARTIFACTS = True
CORS_ALLOWED_ORIGIN = "*"
