FRAME_SAMPLE_FPS = 2.0

CROP_X = 1470
CROP_Y = 0
CROP_W = 450
CROP_H = 225

DEDUPE_WINDOW_SECONDS = 2.0
MERGE_WINDOW_SECONDS = 8.0
CLIP_PRE_SECONDS = 15.0
CLIP_POST_SECONDS = 0.0
FUZZY_MATCH_THRESHOLD = 78
SQS_VISIBILITY_TIMEOUT_SECONDS = 1800

LOCAL_TEMP_DIR = "./temp"
LOG_LEVEL = "INFO"
